runtime: php55
api_version: 1
handlers:
  - url: /home
    script: home.php
  - url: /create
    script: create.php
  - url: /delete
    script: delete.php
  - url: /test
    script: test.php
  - url: /sample
    script: sample.php
